### ISSUE TITLE
Wallbash not working for non official Hyde themes.

### ISSUE THREAD

**Issue by 3laws** [kRHYME7/hyde-gallery#5]
Steps to recreate:

1. Select _theme_ on wallbash
![240506_12h21m07s_screenshot](https://github.com/kRHYME7/hyde-gallery/assets/4267075/b0a1bd58-7e7c-4707-920e-cf400c14e031)

2. Swap theme to official Hyde theme
 ![240506_12h14m26s_screenshot](https://github.com/kRHYME7/hyde-gallery/assets/4267075/7ee43290-9acf-4cfc-bb4d-ba1fa0dc0a02)

3. Swap theme to Dracula (in this case), wallbash does not respect _theme_ and only _auto_ works
![240506_12h18m19s_screenshot](https://github.com/kRHYME7/hyde-gallery/assets/4267075/d8dd6c45-7286-4ce9-aedd-fa7417078795)

**Comment by 3laws** [comment]
`$ Hyde wallbash toggle `

`environment: line 1: {: command not found
environment: line 4: : No such file or directory
sed: can't read : No such file or directory
environment: eval: line 1: syntax error near unexpected token `('
environment: eval: line 1: `target=@define-color bar-bg rgba(0, 0, 0, 0);'
environment: line 1: =: command not found
environment: line 4: : No such file or directory
sed: can't read : No such file or directory
environment: eval: line 1: syntax error near unexpected token `newline'
environment: eval: line 1: `target=<?xml version="1.0" encoding="UTF-8" standalone="no"?>'
[skip] "/home/3laws/.config/cava/Wall-Dcol"
[skip] "/home/3laws/.config/spicetify/Themes/Sleek/color.ini"`

**Comment by 3laws** [comment]
Actually, further testing shows that this only happens with @RAprogramm themes, T-Crypt's ones work as expected.

**Comment by kRHYME7** [comment]
Ops, Never tested it with bare themes all this time. the configs from @RAprogramm  do not have header for targetfiles. 

It should have this in line # 1
![image](https://github.com/kRHYME7/hyde-gallery/assets/53417443/023d9214-e771-4097-b8b5-b53d352b135f)


@RAprogramm 
![image](https://github.com/kRHYME7/hyde-gallery/assets/53417443/fd271b8b-ffa7-4311-9a71-8f5291f063a8)

@3laws  Can you please make an issue into his repo?

**Comment by RAprogramm** [comment]
> Ops, Never tested it with bare themes all this time. the configs from @RAprogramm  do not have header for targetfiles. 
> 
> It should have this in line # 1
> ![image](https://github.com/kRHYME7/hyde-gallery/assets/53417443/023d9214-e771-4097-b8b5-b53d352b135f)
> 
> 
> @RAprogramm 
> ![image](https://github.com/kRHYME7/hyde-gallery/assets/53417443/fd271b8b-ffa7-4311-9a71-8f5291f063a8)
> 
> @3laws  Can you please make an issue into his repo?

Guys,  I got you! Try to fix that! Thank you

**Comment by RAprogramm** [comment]
It was not added config pathes at all! I fix it and now all works good.
Check this out, guys! 
One more time thank you for attention!

**Comment by 3laws** [comment]
Tnx it works! I will add an issue on his repo for a resulting visibility issue.
