### ISSUE TITLE
Theme caused lagging on Right-Click.

### ISSUE THREAD

**Issue by abenezerw** [kRHYME7/hyde-gallery#8]
Hey @kRHYME7  Khing,
If you open an app like dolphin which has the themed out right click, with the Nordic or dracula theme, the right click inside those apps will have extreme lag, through out pc, you have to wait for delay after it goes away you can click on other stuff.
I suspect its because of blur on the right click menu borders, the two themes above are the only ones with thick blurred borders.

**Comment by kRHYME7** [comment]
Cool In readme we have the owners of those themes please report those issues to the respective repo too. Will try to see if I can debug this.

**Comment by kRHYME7** [comment]
Hey @abenezerw. I've tested both the themes and can't replicate those issues.  I'm running  ` hyprland-git ` .

Can you try to disable some intensive  features using this command?   
![image](https://github.com/kRHYME7/hyde-gallery/assets/53417443/0cf1fc5d-2211-4ba4-9672-36de306a0ba4)

**Comment by abenezerw** [comment]
For dracula sure, but Nordic blue is the same og one from HyDe right?
and to be sure you went into dolphin with those themes and right clicked a folder and tried selecting options and had no lag?

**Comment by kRHYME7** [comment]
yes I got no lag.

try to delete all those themes and `Hyde theme patch `  those themes

**Comment by abenezerw** [comment]
ok i guess just my pc maybe, ill ask the other repos
